### ISSUE TITLE
What is the copyright license of the fonts used?

### ISSUE THREAD

**Issue by openarun** [linuxdeepin/deepin-deb-installer#14]
Hello there,
I see that there are two TTF font files in assets/font/
SourceHanSansCN-Medium.ttf
SourceHanSansCN-Normal.ttf 

I would like to know what license are those files released and their copyright?
Thanks!

**Comment by xmuli** [comment]
[LICENSE](https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt) ?

**Comment by ClayStan** [comment]
We will add the license of fonts tomorrow.

**Comment by crazy-noray** [comment]
Thanks for your reminder, we have been delete the font from application.

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
