### ISSUE TITLE
带交互的deb安装问题

### ISSUE THREAD

**Issue by tph85666031** [linuxdeepin/deepin-deb-installer#17]
带交互的deb安装时，输入交互数据后点击 确定按钮没反应。
版本是 uos软件包安装器 5.7.0.20

**Comment by zhangkai749** [comment]
您好，交互配置包的配置内容等相对比较复杂，新版本已经优化过，请您再试下，若还是无法安装，请提供下安装包，研发人员会进行跟踪处理这个问题

**Comment by zhangkai749** [comment]
> 带交互的deb安装时，输入交互数据后点击 确定按钮没反应。
> 版本是 uos软件包安装器 5.7.0.20

您好，交互配置包的配置内容等相对比较复杂，新版本已经优化过，请您再试下，若还是无法安装，请提供下安装包，研发人员会进行跟踪处理这个问题

**Comment by Sky-Asher** [comment]
已超过1个月无人反馈，此问题即将关闭，感谢您的支持。
