### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yangfl** [linuxdeepin/deepin-deb-installer#2]
./packagesmanager.cpp:327: choosed  ==> chose, chosen
./packagesmanager.cpp:338: choosed  ==> chose, chosen
./packagesmanager.cpp:362: choosed  ==> chose, chosen
./packagesmanager.cpp:368: choosed  ==> chose, chosen
./packagesmanager.cpp:525: availble  ==> available
./packagesmanager.cpp:543: choosed  ==> chose, chosen
./deblistmodel.cpp:410: availble  ==> available

**Comment by amsokol** [comment]
./filechoosewidget.cpp:104: Pakcage ==> Package

**Comment by BLumia** [comment]
Whoops, will fix it later, patches are welcome btw :)

**Comment by amsokol** [comment]
Hi, I can easy fix it. Should I create pull request here or use https://cr.wh-redirect.deepin.cn/admin/projects/deepin-deb-installer?

**Comment by BLumia** [comment]
> Hi, I can easy fix it. Should I create pull request here or use https://cr.wh-redirect.deepin.cn/admin/projects/deepin-deb-installer?

GitHub Pull Request will be good.

**Comment by amsokol** [comment]
Done. Pull request is waiting for approval.
