### ISSUE TITLE
"Update" instead of "Reinstall" when installing newer package.

### ISSUE THREAD

**Issue by DanyGee** [linuxdeepin/deepin-deb-installer#3]
When installing newer package, the button on the right could say `Update` instead of `Reinstall`.
`Reinstall` should be reserved for the same package install.
Didn't try this, but if it is possible to install older package version, the button could say `Downgrade`.
I think this little change will confuse users a bit less 😊

**Comment by z966768** [comment]
Thank you for your opinion, we will communicate with the product manager whether this change is reasonable

**Comment by z966768** [comment]
We have decided to apply this suggestion, thank you for your suggestion and will modify it in the future
